name: Publish Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [8]
        type: [jdk, jre]
        os: [alpine, debian]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.versions }}/${{ matrix.type }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          govpf/openjdk:${{ matrix.versions }}-${{ matrix.type }}-${{ matrix.os }}
    -
      name: Push aliases
      uses: docker/build-push-action@v2
      if: matrix.os == 'debian'
      with:
        context: .
        file: ./${{ matrix.versions }}/${{ matrix.type }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          govpf/openjdk:${{ matrix.versions }}-${{ matrix.type }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: govpf/debian
